<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('cursos', function (Blueprint $table) {
            // id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
            $table->id();

            // nome_curso VARCHAR(100) UNIQUE NOT NULL
            $table->string('nome_curso', 100)->unique();

            // descricao TEXT
            $table->text('descricao')->nullable(); 

            // area TEXT
            $table->text('area')->nullable(); 

            // ativo BOOLEAN NOT NULL DEFAULT TRUE
            $table->boolean('ativo')->default(true);

            // criado_em e atualizado_em (TIMESTAMPTZ)
            // O timestamps() do Laravel cria 'created_at' e 'updated_at' automaticamente
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('cursos');
    }
};
