<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('modulos', function (Blueprint $table) {
            // BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
            $table->id();

            // id_curso BIGINT NOT NULL REFERENCES curso(id) ON DELETE CASCADE
            // Mudei o nome de id_curso para curso_id para seguir a convenção do Laravel
            // Assim o laravel vai reconhecer automaticamente que a coluna é uma foreign key
            $table->foreignId('curso_id')->constrained('cursos')->onDelete('cascade');

            // ordem INT NOT NULL CHECK (ordem > 0) 
            // Constraint implementada abaixo via DB::statement
            $table->integer('ordem');

            $table->text('titulo');
            $table->text('descricao')->nullable();
            $table->boolean('ativo')->default(true);
            
            // criado_em e atualizado_em
            $table->timestamps();

            // CONSTRAINT uq_modulo_ordem UNIQUE (id_curso, ordem)
            $table->unique(['curso_id', 'ordem']);

            // CONSTRAINT uq_modulo_titulo UNIQUE (id_curso, titulo)
            $table->unique(['curso_id', 'titulo']);
        });

        // Adicionando as restrições CHECK conforme o diagrama DER
        DB::statement("ALTER TABLE modulos ADD CONSTRAINT ck_modulo_ordem_positiva 
            CHECK (ordem > 0)");
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('modulos');
    }
};
